# Generated by Django 2.2.11 on 2020-03-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newspage',
            unique_together={('news', 'page')},
        ),
        migrations.AlterUniqueTogether(
            name='relatednews',
            unique_together={('news', 'url')},
        ),
    ]
