# Generated by Django 2.2.11 on 2020-03-21 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0002_auto_20200321_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spotlights.Section'),
            preserve_default=False,
        ),
    ]
