# Generated by Django 2.2.11 on 2020-03-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0002_auto_20200324_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='slug'),
        ),
    ]
