# Generated by Django 2.2.11 on 2020-03-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0003_news_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='blurb',
            field=models.CharField(blank=True, max_length=100, verbose_name='blurb'),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=100, verbose_name='headline'),
        ),
        migrations.AlterField(
            model_name='news',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotlights.Section'),
        ),
    ]
