# Generated by Django 2.2.11 on 2020-03-22 12:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0004_auto_20200321_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotlights.Section'),
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotlights.Section')),
            ],
            options={
                'verbose_name': 'layout',
                'verbose_name_plural': 'layouts',
            },
        ),
    ]
