# Generated by Django 2.2.11 on 2020-03-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0005_auto_20200322_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spotlights.Site'),
            preserve_default=False,
        ),
    ]
