# Generated by Django 2.2.11 on 2020-03-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0006_layout_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotlights.Layout'),
        ),
    ]
