# Generated by Django 2.2.11 on 2020-03-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0007_news_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news', verbose_name='image'),
        ),
    ]
