# Generated by Django 2.2.11 on 2020-03-22 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0008_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('headline', models.CharField(max_length=100, verbose_name='headline')),
                ('url', models.URLField(verbose_name='url')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotlights.News')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
