# Generated by Django 2.2.11 on 2020-03-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0009_relatednews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='relatednews',
            options={'verbose_name': 'related news', 'verbose_name_plural': 'related news'},
        ),
        migrations.AddField(
            model_name='news',
            name='supersede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotlights.News'),
        ),
        migrations.AlterField(
            model_name='news',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotlights.Layout'),
        ),
        migrations.AlterField(
            model_name='news',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotlights.Section'),
        ),
    ]
