# Generated by Django 2.2.11 on 2020-03-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0010_auto_20200323_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='supersede',
        ),
    ]
