# Generated by Django 2.2.11 on 2020-03-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0012_auto_20200323_2007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Panel',
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'verbose_name': 'panel', 'verbose_name_plural': 'panels'},
        ),
        migrations.RenameField(
            model_name='layout',
            old_name='section',
            new_name='panel',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='section',
            new_name='panel',
        ),
    ]
