# Generated by Django 2.2.11 on 2020-03-23 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0015_auto_20200323_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spotlights.Page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='editorials',
            field=models.ManyToManyField(to='spotlights.Editorial'),
        ),
        migrations.AlterField(
            model_name='page',
            name='editorials',
            field=models.ManyToManyField(to='spotlights.Editorial'),
        ),
    ]
