# Generated by Django 2.2.11 on 2020-03-23 22:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0016_auto_20200323_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotlights.Site')),
            ],
            options={
                'verbose_name': 'tag page',
                'verbose_name_plural': 'tag pages',
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='page',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='news',
            name='tag_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotlights.TagPage'),
        ),
    ]
