# Generated by Django 2.2.11 on 2020-03-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0017_auto_20200323_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tag_page',
        ),
        migrations.DeleteModel(
            name='TagPage',
        ),
    ]
