# Generated by Django 2.2.11 on 2020-03-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0018_auto_20200323_2220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editorial',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='editorials',
            new_name='tags',
        ),
    ]
